version: '3.8'
services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'carsome_transit'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - '1000:3306'
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    links:
      - 'mysql:mysql'
    depends_on:
      - mysql
